export enum Constants {
  SIGN_IN_ERROR = 'SIGN_IN_ERROR',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS',
  SIGN_OUT_ERROR = 'SIGN_OUT_ERROR',

  FETCHING_LOCATION = 'FETCHING_LOCATION',
  LOCATION_FETCHED = 'LOCATION_FETCHED',
  LOCATION_NOT_FETCHED = 'LOCATION_NOT_FETCHED',

  SPOT_WAS_RECORDED = 'SPOT_WAS_RECORDED',

  CENTER_WAS_RECORDED = 'CENTER_WAS_RECORDED'
}
